version: '3'

services:
  app: 
    build:
      context: .
    ports:
      - 8001:8001
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=dockerdb
